<a href="https://colab.research.google.com/github/saizaylinnhtet/Pytorch/blob/main/pytorch_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Imports


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


# Tensors


In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# tensor back as python code
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,2,1],[3,4,4,1],[5,6,6,5],[1,1,1,1],[0,0,0,0]],[[1,2,3,4],[3,4,5,6],[3,3,3,3],[4,4,4,4],[5,5,5,5]]])
TENSOR

tensor([[[1, 2, 2, 1],
         [3, 4, 4, 1],
         [5, 6, 6, 5],
         [1, 1, 1, 1],
         [0, 0, 0, 0]],

        [[1, 2, 3, 4],
         [3, 4, 5, 6],
         [3, 3, 3, 3],
         [4, 4, 4, 4],
         [5, 5, 5, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 5, 4])

In [ ]:
# Random Tensors
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3037, 0.6503, 0.7030, 0.2364],
        [0.8439, 0.8511, 0.7357, 0.3639],
        [0.0487, 0.4136, 0.6660, 0.4054]])

In [ ]:
random_tensor = torch.rand(3,5,2)
random_tensor

tensor([[[0.9844, 0.4660],
         [0.4496, 0.8654],
         [0.4620, 0.2751],
         [0.6662, 0.0831],
         [0.6219, 0.2440]],

        [[0.7408, 0.8702],
         [0.2400, 0.4546],
         [0.8918, 0.5280],
         [0.2450, 0.4348],
         [0.5300, 0.4042]],

        [[0.9242, 0.3217],
         [0.5447, 0.6334],
         [0.7649, 0.2674],
         [0.8682, 0.1518],
         [0.8211, 0.9657]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# Random Tensor With Similar Shape To Image Tensor
random_img_size_tensor = torch.rand(size=(3,224,224)) # color (R,G,B), height, width
random_img_size_tensor, random_img_size_tensor.shape, random_img_size_tensor.ndim

(tensor([[[0.3157, 0.4822, 0.3292,  ..., 0.4262, 0.4477, 0.1419],
          [0.3316, 0.2035, 0.2353,  ..., 0.5440, 0.8234, 0.7049],
          [0.0014, 0.5731, 0.9923,  ..., 0.0351, 0.5901, 0.2389],
          ...,
          [0.5901, 0.7128, 0.1819,  ..., 0.1833, 0.6440, 0.4585],
          [0.6254, 0.4113, 0.6119,  ..., 0.1063, 0.0492, 0.9162],
          [0.1769, 0.8104, 0.6029,  ..., 0.0810, 0.4459, 0.5946]],
 
         [[0.0465, 0.5221, 0.0957,  ..., 0.2748, 0.0411, 0.9767],
          [0.3733, 0.1654, 0.7550,  ..., 0.4088, 0.4495, 0.6892],
          [0.7772, 0.7693, 0.1089,  ..., 0.3162, 0.8187, 0.1899],
          ...,
          [0.1473, 0.7247, 0.5790,  ..., 0.3140, 0.0289, 0.5363],
          [0.0884, 0.0280, 0.2582,  ..., 0.2288, 0.5390, 0.5370],
          [0.1332, 0.9704, 0.0565,  ..., 0.1917, 0.4264, 0.5350]],
 
         [[0.1461, 0.6908, 0.8622,  ..., 0.1779, 0.0253, 0.0148],
          [0.3582, 0.4523, 0.6079,  ..., 0.9766, 0.8950, 0.2916],
          [0.5273, 0.4794, 0.8666,  ...,

In [ ]:
# Zeroes
zeroes = torch.zeros(4,3)
zeroes

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# Ones
ones = torch.ones(4,3)
ones, ones.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

In [ ]:
# Range
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
step = torch.arange(start=1, end=1000, step=100)
step

tensor([  1, 101, 201, 301, 401, 501, 601, 701, 801, 901])

In [ ]:
#  Tensor Like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Tensor Attributes
float_32_tensor = torch.tensor([1,0,2.0,3.0], dtype=None, device=None, requires_grad=False)
# dtype(torch.float32,torch.float16,torch.float64,etc)
# device(cpu,cuda,etc)
# requires_grad for track gradients with this tensor operation
float_32_tensor, float_32_tensor.dtype

(tensor([1., 0., 2., 3.]), torch.float32)

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 0., 2., 3.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([1., 0., 4., 9.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * float_16_tensor

tensor([1., 0., 4., 9.])

In [ ]:
# Tensor Operations
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [ ]:
tensor - 1

tensor([0, 1, 2])

In [ ]:
tensor * 100

tensor([100, 200, 300])

In [ ]:
tensor / 2

tensor([0.5000, 1.0000, 1.5000])

In [ ]:
# Matrix Multiplication (1. element-wise multiplication, 2. matrix multiplication(dot product))

# 1. Element-Wise Multiplication
print(tensor,' * ',tensor,' is ',(tensor * tensor) )

tensor([1, 2, 3])  *  tensor([1, 2, 3])  is  tensor([1, 4, 9])


In [ ]:
# 2. Matrix Multiplication
torch.matmul(tensor,tensor) # 1*1 + 2*2 + 3*3

tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
# Reshape, Stacking, Squeezing and Unsqueezing Tensors
x = torch.arange(1,10)
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
x_reshape = x.reshape(1,9)
x_reshape, x_reshape.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
x_reshape2 = x.reshape(9,1)
x_reshape2, x_reshape2.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [ ]:
x_reshape3 = x.reshape(3,3)
x_reshape3, x_reshape3.shape, x_reshape3.ndim

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]),
 2)

In [ ]:
z = x.view(1,9) # view share the same memory as original tensor, changing the view will also change the original tensor
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
x_stack = torch.stack([x, x, x], dim=0)
x_stack

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_stack2 = torch.stack([x,x,x], dim=1)
x_stack2

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]])